# -*- coding: utf-8 -*-
"""villagerData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wehyM9FAdTBf4mhgNOUXYWgRLBjSgV1T
"""

import pandas as pd

def simulate_price(base_price, price_multiplier, villager_level, max_trades, villager_name="villager", trade_name="trade",  base_item="emerald"):
  # define uma função chamada simulate_price com os parâmetros (dados a serem inseridos) base_price,
  # price, multiplier, max_trades e trade_name. se nada for inserido para trade_name, o valor padrão 'trade' é adotado.

  results = []
  # cria uma lista/vetor vazio.

  demand = 0
  # determina 0 como valor inicial da variável demand.

  for buy in range(1, max_trades + 1):
    # esse for repete o código abaixo uma vez a cada compra feita até o limite de compras/trades, determinado pelo parâmetro
    # max_trades. o +1 serve pra incluir o último número, pq o python só vai até o range fornecido, mas não inclui ele.

    increase = int(price_multiplier * demand * base_price)
    # fórmula do aumento de preço, multiplicador de preço vezes a demanda vezes o preço base.

    paid_price = base_price + increase
    # total pago.

    results.append({
        "villager": villager_name,
        "level": villager_level,
        "trade": trade_name,
        "base item": base_item,
        "buy": buy,
        "demand": demand,
        "increase": increase,
        "price": paid_price
    })
    # adiciona ao final da lista results cada um dos items (no caso um dicionario) onde cada chave (primeiro item)
    # tem seu valor (segundo item).

    demand+= 1
    #incrementa a demanda em +1, pois a cada item comprado a demanda aumenta em 1.

  return results

# ARMORER == ARMORER == ARMORER == ARMORER == ARMORER == ARMORER == ARMORER ==

all_trades = [
   {
    "villager_name": "Armorer",
    "villager_level": "Novice",
    "trade_name": "Emerald",
    "base_item": "Coal",
    "base_price": 15,
    "price_multiplier": 0.05,
    "max_trades": 16
},
{
    "villager_name": "Armorer",
    "villager_level": "Novice",
    "trade_name": "Iron Helmet",
    "base_item": "Emerald",
    "base_price": 5,
    "price_multiplier": 0.2,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Novice",
    "trade_name": "Iron Chestplate",
    "base_item": "Emerald",
    "base_price": 9,
    "price_multiplier": 0.2,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Novice",
    "trade_name": "Iron Leggings",
    "base_item": "Emerald",
    "base_price": 7,
    "price_multiplier": 0.2,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Novice",
    "trade_name": "Iron Boots",
    "base_item": "Emerald",
    "base_price": 4,
    "price_multiplier": 0.2,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Apprentice",
    "trade_name": "Emerald",
    "base_item": "Iron Ingot",
    "base_price": 4,
    "price_multiplier": 0.05,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Apprentice",
    "trade_name": "Chainmail Leggings",
    "base_item": "Emerald",
    "base_price": 3,
    "price_multiplier": 0.2,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Apprentice",
    "trade_name": "Chainmail Boots",
    "base_item": "Emerald",
    "base_price": 1,
    "price_multiplier": 0.2,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Journeyman",
    "trade_name": "Emerald",
    "base_item": "Lava Bucket",
    "base_price": 1,
    "price_multiplier": 0.05,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Journeyman",
    "trade_name": "Emerald",
    "base_item": "Diamond",
    "base_price": 1,
    "price_multiplier": 0.05,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Journeyman",
    "trade_name": "Chainmail Helmet",
    "base_item": "Emerald",
    "base_price": 1,
    "price_multiplier": 0.2,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Journeyman",
    "trade_name": "Chainmail Chestplate",
    "base_item": "Emerald",
    "base_price": 4,
    "price_multiplier": 0.2,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Journeyman",
    "trade_name": "Shield",
    "base_item": "Emerald",
    "base_price": 5,
    "price_multiplier": 0.2,
    "max_trades": 12
},
{
    "villager_name": "Armorer",
    "villager_level": "Expert",
    "trade_name": "Enchanted Diamond Leggings",
    "base_item": "Emerald",
    "base_price": 20,
    "price_multiplier": 0.2,
    "max_trades": 3
},
{
    "villager_name": "Armorer",
    "villager_level": "Expert",
    "trade_name": "Enchanted Diamond Boots",
    "base_item": "Emerald",
    "base_price": 21,
    "price_multiplier": 0.2,
    "max_trades": 3
},
{
    "villager_name": "Armorer",
    "villager_level": "Master",
    "trade_name": "Enchanted Diamond Helmet",
    "base_item": "Emerald",
    "base_price": 21,
    "price_multiplier": 0.2,
    "max_trades": 3
    },
    {
        "villager_name": "Armorer",
        "villager_level": "Master",
        "trade_name": "Enchanted Diamond Chestplate",
        "base_item": "Emerald",
        "base_price": 30,
        "price_multiplier": 0.2,
        "max_trades": 3
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Raw Chicken",
        "base_price": 14,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Raw Porkchop",
        "base_price": 7,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Raw Rabbit",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Novice",
        "trade_name": "Rabbit Stew",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Coal",
        "base_price": 15,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Apprentice",
        "trade_name": "Cooked Porkchop",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Apprentice",
        "trade_name": "Cooked Chicken",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Raw Mutton",
        "base_price": 7,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Raw Beef",
        "base_price": 10,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Dried Kelp Block",
        "base_price": 10,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Butcher",
        "villager_level": "Master",
        "trade_name": "Emerald",
        "base_item": "Sweet Berries",
        "base_price": 10,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Paper",
        "base_price": 24,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Novice",
        "trade_name": "Empty Map",
        "base_item": "Emerald",
        "base_price": 7,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Glass Pane",
        "base_price": 11,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Apprentice",
        "trade_name": "Explorer Map",
        "base_item": "Emerald + Compass",
        "base_price": 8,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Compass",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Journeyman",
        "trade_name": "Ocean Explorer Map",
        "base_item": "Emerald + Compass",
        "base_price": 13,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Journeyman",
        "trade_name": "Trial Explorer Map",
        "base_item": "Emerald + Compass",
        "base_price": 12,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Expert",
        "trade_name": "Item Frame",
        "base_item": "Emerald",
        "base_price": 7,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Expert",
        "trade_name": "Banner",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Master",
        "trade_name": "Globe Banner Pattern",
        "base_item": "Emerald",
        "base_price": 8,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cartographer",
        "villager_level": "Master",
        "trade_name": "Woodland Explorer Map",
        "base_item": "Emerald + Compass",
        "base_price": 14,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Rotten Flesh",
        "base_price": 32,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Novice",
        "trade_name": "Redstone Dust",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Gold Ingot",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Apprentice",
        "trade_name": "Lapis Lazuli",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Rabbit's Foot",
        "base_price": 2,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Journeyman",
        "trade_name": "Glowstone",
        "base_item": "Emerald",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Turtle Scute",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Glass Bottle",
        "base_price": 9,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Expert",
        "trade_name": "Ender Pearl",
        "base_item": "Emerald",
        "base_price": 5,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Master",
        "trade_name": "Emerald",
        "base_item": "Nether Wart",
        "base_price": 22,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Cleric",
        "villager_level": "Master",
        "trade_name": "Bottle o' Enchanting",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Wheat",
        "base_price": 20,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Potato",
        "base_price": 26,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Carrot",
        "base_price": 22,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Beetroot",
        "base_price": 15,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Novice",
        "trade_name": "Bread",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Pumpkin",
        "base_price": 6,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Apprentice",
        "trade_name": "Pumpkin Pie",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Apprentice",
        "trade_name": "Apple",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Melon",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Journeyman",
        "trade_name": "Cookie",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Expert",
        "trade_name": "Suspicious Stew",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Expert",
        "trade_name": "Cake",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Master",
        "trade_name": "Golden Carrot",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Farmer",
        "villager_level": "Master",
        "trade_name": "Glistering Melon Slice",
        "base_item": "Emerald",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "String",
        "base_price": 20,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Coal",
        "base_price": 10,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Novice",
        "trade_name": "Cooked Cod",
        "base_item": "Raw Cod + Emerald",
        "base_price": 6,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Novice",
        "trade_name": "Bucket of Cod",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Raw Cod",
        "base_price": 15,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Apprentice",
        "trade_name": "Campfire",
        "base_item": "Emerald",
        "base_price": 2,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Apprentice",
        "trade_name": "Cooked Salmon",
        "base_item": "Raw Salmon + Emerald",
        "base_price": 6,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Raw Salmon",
        "base_price": 13,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Journeyman",
        "trade_name": "Enchanted Fishing Rod",
        "base_item": "Emerald",
        "base_price": 16,
        "price_multiplier": 0.2,
        "max_trades": 3
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Tropical Fish",
        "base_price": 6,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Master",
        "trade_name": "Emerald",
        "base_item": "Pufferfish",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Master",
        "trade_name": "Emerald",
        "base_item": "Oak Boat",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Master",
        "trade_name": "Emerald",
        "base_item": "Spruce Boat",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Master",
        "trade_name": "Emerald",
        "base_item": "Jungle Boat",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Master",
        "trade_name": "Emerald",
        "base_item": "Acacia Boat",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fisherman",
        "villager_level": "Master",
        "trade_name": "Emerald",
        "base_item": "Dark Oak Boat",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Stick",
        "base_price": 32,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Novice",
        "trade_name": "Arrow",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Novice",
        "trade_name": "Flint",
        "base_item": "Emerald + Gravel",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Flint",
        "base_price": 26,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Apprentice",
        "trade_name": "Bow",
        "base_item": "Emerald",
        "base_price": 2,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "String",
        "base_price": 14,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Journeyman",
        "trade_name": "Crossbow",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Feather",
        "base_price": 24,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Expert",
        "trade_name": "Enchanted Bow",
        "base_item": "Emerald",
        "base_price": 7,
        "price_multiplier": 0.05,
        "max_trades": 3
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Master",
        "trade_name": "Emerald",
        "base_item": "Tripwire Hook",
        "base_price": 8,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Master",
        "trade_name": "Enchanted Crossbow",
        "base_item": "Emerald",
        "base_price": 8,
        "price_multiplier": 0.05,
        "max_trades": 3
    },
    {
        "villager_name": "Fletcher",
        "villager_level": "Master",
        "trade_name": "Tipped Arrow",
        "base_item": "Emerald + Arrow",
        "base_price": 2,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Leather",
        "base_price": 6,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Novice",
        "trade_name": "Leather Pants",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Novice",
        "trade_name": "Leather Tunic",
        "base_item": "Emerald",
        "base_price": 7,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Flint",
        "base_price": 26,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Apprentice",
        "trade_name": "Leather Cap",
        "base_item": "Emerald",
        "base_price": 5,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Apprentice",
        "trade_name": "Leather Boots",
        "base_item": "Emerald",
        "base_price": 4,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Rabbit Hide",
        "base_price": 9,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Journeyman",
        "trade_name": "Leather Tunic",
        "base_item": "Emerald",
        "base_price": 7,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Turtle Scute",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Expert",
        "trade_name": "Leather Horse Armor",
        "base_item": "Emerald",
        "base_price": 6,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Master",
        "trade_name": "Leather Cap",
        "base_item": "Emerald",
        "base_price": 5,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Leatherworker",
        "villager_level": "Master",
        "trade_name": "Saddle",
        "base_item": "Emerald",
        "base_price": 6,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Paper",
        "base_price": 24,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Novice",
        "trade_name": "Bookshelf",
        "base_item": "Emerald",
        "base_price": 9,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Novice",
        "trade_name": "Enchanted Book",
        "base_item": "Emerald + Book",
        "base_price": 35,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Book",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Apprentice",
        "trade_name": "Lantern",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Apprentice",
        "trade_name": "Enchanted Book",
        "base_item": "Emerald + Book",
        "base_price": 35,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Ink Sac",
        "base_price": 5,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Journeyman",
        "trade_name": "Glass",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Journeyman",
        "trade_name": "Enchanted Book",
        "base_item": "Emerald + Book",
        "base_price": 35,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Book and Quill",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Expert",
        "trade_name": "Compass",
        "base_item": "Emerald",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Expert",
        "trade_name": "Clock",
        "base_item": "Emerald",
        "base_price": 5,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Expert",
        "trade_name": "Enchanted Book",
        "base_item": "Emerald + Book",
        "base_price": 35,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Master",
        "trade_name": "Red Candle",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Librarian",
        "villager_level": "Master",
        "trade_name": "Yellow Candle",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Mason",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Clay Ball",
        "base_price": 10,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Novice",
        "trade_name": "Brick",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Stone",
        "base_price": 20,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Apprentice",
        "trade_name": "Chiseled Stone Bricks",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Granite",
        "base_price": 16,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Andesite",
        "base_price": 16,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Diorite",
        "base_price": 16,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Journeyman",
        "trade_name": "Dripstone Block",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Journeyman",
        "trade_name": "Polished Andesite",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Journeyman",
        "trade_name": "Polished Diorite",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Journeyman",
        "trade_name": "Polished Granite",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Mason",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Nether Quartz",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Mason",
        "villager_level": "Expert",
        "trade_name": "Stained Terracotta",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Mason",
        "villager_level": "Expert",
        "trade_name": "Glazed Terracotta",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Mason",
        "villager_level": "Master",
        "trade_name": "Quartz Pillar",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Mason",
        "villager_level": "Master",
        "trade_name": "Block of Quartz",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "White Wool",
        "base_price": 18,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Brown Wool",
        "base_price": 18,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Black Wool",
        "base_price": 18,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Gray Wool",
        "base_price": 18,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Novice",
        "trade_name": "Shears",
        "base_item": "Emerald",
        "base_price": 2,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "White Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Gray Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Black Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Light Blue Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Lime Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Apprentice",
        "trade_name": "Wool",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Apprentice",
        "trade_name": "Carpet",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Yellow Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Light Gray Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Orange Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Red Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Pink Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Journeyman",
        "trade_name": "Bed",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Brown Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Purple Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Blue Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Green Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Magenta Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Cyan Dye",
        "base_price": 12,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Expert",
        "trade_name": "Banner",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Shepherd",
        "villager_level": "Master",
        "trade_name": "Painting",
        "base_item": "Emerald",
        "base_price": 2,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Coal",
        "base_price": 15,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Novice",
        "trade_name": "Stone Axe",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Novice",
        "trade_name": "Stone Shovel",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Novice",
        "trade_name": "Stone Pickaxe",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Novice",
        "trade_name": "Stone Hoe",
        "base_item": "Emerald",
        "base_price": 1,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Iron Ingot",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Apprentice",
        "trade_name": "Bell",
        "base_item": "Emerald",
        "base_price": 36,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Flint",
        "base_price": 30,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Journeyman",
        "trade_name": "Enchanted Iron Axe",
        "base_item": "Emerald",
        "base_price": 13,
        "price_multiplier": 0.2,
        "max_trades": 3
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Journeyman",
        "trade_name": "Enchanted Iron Shovel",
        "base_item": "Emerald",
        "base_price": 14,
        "price_multiplier": 0.2,
        "max_trades": 3
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Journeyman",
        "trade_name": "Enchanted Iron Pickaxe",
        "base_item": "Emerald",
        "base_price": 15,
        "price_multiplier": 0.2,
        "max_trades": 3
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Journeyman",
        "trade_name": "Diamond Hoe",
        "base_item": "Emerald",
        "base_price": 4,
        "price_multiplier": 0.2,
        "max_trades": 3
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Diamond",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Expert",
        "trade_name": "Enchanted Diamond Axe",
        "base_item": "Emerald",
        "base_price": 24,
        "price_multiplier": 0.2,
        "max_trades": 3
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Expert",
        "trade_name": "Enchanted Diamond Shovel",
        "base_item": "Emerald",
        "base_price": 17,
        "price_multiplier": 0.2,
        "max_trades": 3
    },
    {
        "villager_name": "Toolsmith",
        "villager_level": "Master",
        "trade_name": "Enchanted Diamond Pickaxe",
        "base_item": "Emerald",
        "base_price": 25,
        "price_multiplier": 0.2,
        "max_trades": 3
    },
    {
        "villager_name": "Weaponsmith",
        "villager_level": "Novice",
        "trade_name": "Emerald",
        "base_item": "Coal",
        "base_price": 15,
        "price_multiplier": 0.05,
        "max_trades": 16
    },
    {
        "villager_name": "Weaponsmith",
        "villager_level": "Novice",
        "trade_name": "Iron Axe",
        "base_item": "Emerald",
        "base_price": 3,
        "price_multiplier": 0.2,
        "max_trades": 12
    },
    {
        "villager_name": "Weaponsmith",
        "villager_level": "Novice",
        "trade_name": "Enchanted Iron Sword",
        "base_item": "Emerald",
        "base_price": 14,
        "price_multiplier": 0.05,
        "max_trades": 3
    },
    {
        "villager_name": "Weaponsmith",
        "villager_level": "Apprentice",
        "trade_name": "Emerald",
        "base_item": "Iron Ingot",
        "base_price": 4,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Weaponsmith",
        "villager_level": "Journeyman",
        "trade_name": "Emerald",
        "base_item": "Flint",
        "base_price": 24,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Weaponsmith",
        "villager_level": "Expert",
        "trade_name": "Emerald",
        "base_item": "Diamond",
        "base_price": 1,
        "price_multiplier": 0.05,
        "max_trades": 12
    },
    {
        "villager_name": "Weaponsmith",
        "villager_level": "Expert",
        "trade_name": "Enchanted Diamond Axe",
        "base_item": "Emerald",
        "base_price": 24,
        "price_multiplier": 0.2,
        "max_trades": 3
    },
    {
        "villager_name": "Weaponsmith",
        "villager_level": "Master",
        "trade_name": "Enchanted Diamond Sword",
        "base_item": "Emerald",
        "base_price": 20,
        "price_multiplier": 0.2,
        "max_trades": 3
    }
]

all_trade_results = []

for trade in all_trades:
  all_trade_results.extend(simulate_price(**trade))

  df = pd.DataFrame(all_trade_results)

# sugestão da IA
df["trade_type"] = df["base item"].apply(
    lambda x: "Player buys" if x == "Emerald" else "Player sells"
)

df.to_csv("villager_economy.csv", index=False) # transforma em arquivo csv e tira a linha q mostra os index

from google.colab import files
files.download("villager_economy.csv")